var a;
var b;
var c;
var x;
x = 123;
x = 'sa';
x = false;
var z = [12312, "sadas", false];
var asd = "asdas";
var kP = 0;
var hP = 1;
var eP = 5;
var Payment;
(function (Payment) {
    Payment[Payment["z"] = 0] = "z";
    Payment[Payment["Hp"] = 1] = "Hp";
    Payment[Payment["eP"] = 2] = "eP";
})(Payment || (Payment = {}));
;
var kredi = Payment.Hp;
var havale = Payment.Hp;
var zz = Payment.z;
console.log(kredi);
